apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-custom
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8181
        volumeMounts:
        - name: custom-page
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: custom-page
        configMap:
          name: nginx-custom-page-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-page-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to Nginx!</title>
    </head>
    <body>
        <h1>Custom Nginx Page!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
  type: LoadBalancer
